### ISSUE TITLE
Replace freegeoip.net with freegeoip.live

### ISSUE THREAD

**Issue by incognitte** [openconnect/recipes#9]
The script in [country blocking recipes](https://github.com/openconnect/recipes/blob/master/ocserv-country-blocking.md) refers to freegeoip.net which has been shutdown however freegeoip.live supports the exact same API and can be dropped in with no need to change the rest of script.

Please update the script in both GitHub and Openconnect website.

> GEOIP_STRING=$(curl -s https://freegeoip.live/csv/$IP_REAL)

Thanks

**Comment by nmav** [comment]
Would you like to send a pull request for this?

**Comment by nmav** [comment]
Thank you!
